require('neal.options')
require('neal.keymaps')
require('neal.plugins')
require('neal.cmp')
require('neal.lsp')
require('neal.telescope')
require('neal.treesitter')
require('neal.autopairs')
require('neal.comment')
require('neal.gitsigns')
vim.cmd "colorscheme tokyonight"
